#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


setxkbmap it &
nitrogen --restore
dunst &
picom &
$HOME/Dotfiles/debian-bspwm/Scripts/start_lxaaparence.sh
$HOME/Dotfiles/debian-bspwm/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          10
bspc config top_padding         0
bspc config bottom_padding      0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
