[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#E6B673"
red = "#6C5980"
green = "#54546d"
yellow = "#4C3F47"
blue = "#E6B450"
magenta = "#D4A140"
cyan = "#90734E"
white = "#efdaaf"

[colors.normal]
black = "#363646"
red = "#6C5980"
green = "#957fb8"
yellow = "#7e9cd8"
blue = "#e4d0a8"
magenta = "#D4A140"
cyan = "#F6C457"
white = "#efdaaf"

[colors.primary]
# background = "#0E0E18"
background = "#101010"
foreground = "#ffffff"

