# Gruvbox
# Theme create by: https://github.com/yorukot
# Update by(sort by time):
# 
# Thanks for all contributor!!

# If you want to make border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "gruvbox"

# ========= Border =========
file_panel_border = "#868686"
sidebar_border = "#101010"
footer_border = "#868686"

# ========= Border Active =========
file_panel_border_active = "#FFF1C5"
sidebar_border_active = "#D79921"
footer_border_active = "#D79921"
modal_border_active = "#868686"

# ========= Background (bg) =========
full_screen_bg = "#101010"
file_panel_bg = "#101010"
sidebar_bg = "#101010"
footer_bg = "#101010"
modal_bg = "#101010"

# ========= Foreground (fg) =========
full_screen_fg = "#E6B673"
file_panel_fg = "#E6B673"
sidebar_fg = "#E6B673"
footer_fg = "#E6B673"
modal_fg = "#E6B673"

# ========= Special Color =========
cursor = "#6C5980"
correct = "#6C5980"
error = "#FF6969"
hint = "#957fb8"
cancel = "#838383"
# Gradient color can only have two color!
gradient_color = ["#957fb8", "#fb4934"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#6C5980"
file_panel_top_path = "#957fb8"
file_panel_item_selected_fg = "#D3869B"
file_panel_item_selected_bg = "#101010"

# ========= Sidebar Special Items =========
sidebar_title = "#D4A140"
sidebar_item_selected_fg = "#E8751A"
sidebar_item_selected_bg = "#101010"
sidebar_divider = "#868686"

# ========= Modal Special Items =========
modal_cancel_fg = "#E6B673"
modal_cancel_bg = "#6D6D6D"

modal_confirm_fg = "#E6B673"
modal_confirm_bg = "#FF4D00"

# ========= Help Menu =========
help_menu_hotkey = "#6C5980"
help_menu_title = "#FF4D00"